# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - release
notifications:
  email: true
# uncomment the following lines to override the default test script
# settings from PyCall.jl
env:
  global:
    - PYCALL_DEBUG_BUILD="yes"
  matrix:
    - PYTHON=python  # python 2.7
    - PYTHON=Conda-python # not actually a python version, here to test Conda.jl's python
before_install:
  - test "x$TRAVIS_OS_NAME" = xosx -o "x$PYTHON" = xConda-python || (sudo apt-get -qq update && sudo apt-get install -y $PYTHON)
  - pip install --user --upgrade pip
  - export PATH=$HOME/.local/bin:$PATH
script:
  - git clone https://github.com/openai/gym
  - cd gym
  - pip install -e '.[all]'
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("ReinforcementLearning"); Pkg.test("ReinforcementLearning"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("ReinforcementLearning")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
